### ISSUE TITLE
Start creating a player which will be used as a sandbox to test standard technologies and APIs

### ISSUE THREAD

**Issue by TheAddictedOne** [GroovyHooked/MyPlayer#3]
# Context

To help you grasp Dailymotion products and technologies, building your own custom player is a good sandbox to write code without the fear of breaking the production platform.

# Todo

- [x] Start a fresh project using React. React has a tool to start a project from start. Check `react-create-app`: https://reactjs.org/docs/create-a-new-react-app.html
- [x] Add a `<video>` with a free `.mp4`
- [x] Create a playback button, which will switch from "play" to "pause" state on click
- [x] Bind this playback button to the `<video>` API, to play and pause the video
- [x] Center the playback button. Make it responsive
